### ISSUE TITLE
directory automation doesn't get pulled

### ISSUE THREAD

**Issue by roseswe** [dguitarbite/suse-cloud-hands-on#1]
After a git pull:

suse-cloud-hands-on > tree
.
├── README.md
├── automation
└── deploy-suse-cloud

1 directory, 2 files

**Comment by dguitarbite** [comment]
@roseswe You need to use this command to update the automation directory. This is another git repository and its a git-submodule rather than a folder. Please use the following command:
$ git submodule init && git submodule update

This should clone the automation repository or update it if its already cloned. Please check the script, it does this already:

https://github.com/dguitarbite/suse-cloud-hands-on/blob/master/deploy-suse-cloud#L64
